### ISSUE TITLE
Add types support

### ISSUE THREAD

**Issue by abdonrd** [thepassle/pwa-helpers#12]
To avoid TS errors:

<img width="642" alt="Screenshot 2020-04-26 at 13 48 09" src="https://user-images.githubusercontent.com/1007051/80306605-99174400-87c4-11ea-83a4-abb8191d451a.png">

```
Could not find a declaration file for module 'pwa-helper-components/pwa-install-button.js'. '/Users/abdonrd/.../pwa-starter/node_modules/pwa-helper-components/pwa-install-button.js' implicitly has an 'any' type.
  Try `npm install @types/pwa-helper-components` if it exists or add a new declaration (.d.ts) file containing `declare module 'pwa-helper-components/pwa-install-button.js';`ts(7016)
```

**Comment by thepassle** [comment]
Why does typescript error on this exactly? These are just sideeffectul imports, I would expect typescript to just be compatible with regular JS

**Comment by abdonrd** [comment]
Ops! I forget to add the log! Is this:

```
Could not find a declaration file for module 'pwa-helper-components/pwa-install-button.js'. '/Users/abdonrd/.../pwa-starter/node_modules/pwa-helper-components/pwa-install-button.js' implicitly has an 'any' type.
  Try `npm install @types/pwa-helper-components` if it exists or add a new declaration (.d.ts) file containing `declare module 'pwa-helper-components/pwa-install-button.js';`ts(7016)
```

**Comment by abdonrd** [comment]
> Edit: as a sidenote, I'm not sure how lazy loading pwa-install-button will work out, because it depends on the `beforeinstallprompt` being fired. If you lazyload the component, it becomes a race condition, and theres theoretically a possibility you'll miss it. Not sure if this will actually lead to any problems in your case, just be aware.

Interesting! 🤔

After update to static import is just a note, and not an error:

<img width="788" alt="Screenshot 2020-04-26 at 14 17 36" src="https://user-images.githubusercontent.com/1007051/80307351-cc5bd200-87c8-11ea-9f77-f37f5c4be9a7.png">

**Comment by thepassle** [comment]
For `pwa-update-available` it should be fine to lazyload btw, because it'll just check if theres an existing _and_ waiting serviceworker (which means theres an update available). 

But I still dont understand why TS would fail on that. The import doesnt return anything, it just registers the web component. I'm not really looking forward to jump through a lot of hoops to generate declaration files/add a build step to this project just because TS doesn't support regular JS 🙁 This seems like a big problem with TS to me. I may not understand TS well enough and I could be wrong, but this is the impression I have.

On the other hand, you could wonder if it even makes sense to lazy load these components. They're both only around 30 LoC (thats unminified/gzipped), maybe the cost of lazy loading (connecting to network etc) is more expensive than just including them in your bundle anyway.

**Comment by thepassle** [comment]
You should be able to enable `allowJs` in your tsconfig, I'll close this for now
